[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production"